# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 773971598048fa8dec49a34ed302675442872775edf91c9098bc440150fa8402672b5136f04a12e348cef0ef02f792d0a09d1d07a5caaa2f5d21fcf3aeda825b

test:
  secret_key_base: 8d498ffbe12140f7a168120cffd093cde4302de7cfe8a8d82191db2f50a901577f377b6585be55c98160909b111b0c737e143799e66978358eee2b6836e70f10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
